<?php
/*
Plugin Name: Travel Logic
Plugin URI: http://www.conceptwebsolutions.com/
Description: Travel Logic hotel booking
Author: Concept Web Solutions
Author URI: http://www.conceptwebsolutions.com/
License: GNU GENERAL PUBLIC LICENSE 2.0 or later http://www.gnu.org/licenses/gpl.txt
Version: 1.0
Text Domain: travel-logic
*/

//
// You can override the following constants in
// wp-config.php if you feel the need to.
//
// ***** DO NOT EDIT THIS FILE *****
//

////////////////////////////////
// Important Internal Constants
// *** DO NOT MODIFY THESE ***

// Configuration
define( 'TLOGIC_VERSION', '1.0' );
define( 'TLOGIC_PLUGIN_NAME', 'travel-logic' );
define( 'TLOGIC_PLUGIN_TEXTDOMAIN', 'travel-logic' );
define( 'TLOGIC_PLUGIN_BASENAME', plugin_basename( __FILE__ ) );
define( 'TLOGIC_ASSETS_RELPATH', 'assets' );
define( 'TLOGIC_TPLS_RELPATH', 'templates' );

// Core Paths
define( 'TLOGIC_PLUGIN_DIR', WP_PLUGIN_DIR . '/' . TLOGIC_PLUGIN_NAME );
define( 'TLOGIC_PLUGIN_URL', WP_PLUGIN_URL . '/' . TLOGIC_PLUGIN_NAME );
define( 'TLOGIC_ADMIN_DIR', TLOGIC_PLUGIN_DIR . '/admin' );
define( 'TLOGIC_LIB_DIR', TLOGIC_PLUGIN_DIR . '/lib' );
define( 'TLOGIC_SERVICES_DIR', TLOGIC_PLUGIN_DIR . '/services' );
define( 'TLOGIC_SETTINGS_DIR', TLOGIC_PLUGIN_DIR . '/settings' );

// Sub Paths
define( 'TLOGIC_ASSETS_DIR', TLOGIC_PLUGIN_DIR . '/' . TLOGIC_ASSETS_RELPATH );
define( 'TLOGIC_ASSETS_URL', TLOGIC_PLUGIN_URL . '/' . TLOGIC_ASSETS_RELPATH );
define( 'TLOGIC_TPLS_DIR', TLOGIC_PLUGIN_DIR . '/' . TLOGIC_TPLS_RELPATH );
define( 'TLOGIC_TPLS_URL', TLOGIC_PLUGIN_URL . '/' . TLOGIC_TPLS_RELPATH );

// ***************************
///////////////////////////////

/**
 * Load wp-sdl
 */

require_once TLOGIC_LIB_DIR . '/wp-sdl/wp-sdl.php';

/**
 * Load global functions
 */
require_once TLOGIC_PLUGIN_DIR . '/tl-functions.php';

/**
 * Load settings functions
 */
require_once TLOGIC_PLUGIN_DIR . '/tl-settings.php';

// ajax request?
if ( defined( 'DOING_AJAX' ) && true === DOING_AJAX ) {

	/**
	 * Load ajax files
	 */
	require_once TLOGIC_PLUGIN_DIR . '/tl-classes.php';
	require_once TLOGIC_PLUGIN_DIR . '/tl-ajax.php';

	// load service classes
	tlogic_load_service_classes();

} elseif ( is_admin() ) {

	/**
	 * Load dashboard files
	 */
	require_once TLOGIC_PLUGIN_DIR . '/tl-admin.php';

} else {

	/**
	 * Load front end files
	 */
	require_once TLOGIC_PLUGIN_DIR . '/tl-classes.php';
	require_once TLOGIC_PLUGIN_DIR . '/tl-frontend.php';
	require_once TLOGIC_PLUGIN_DIR . '/tl-ttags.php';

	// load services
	tlogic_load_service_classes();
	tlogic_load_service_frontends();
}

/**
 * Load all service classes.
 */
function tlogic_load_service_classes()
{
    require_once TLOGIC_SERVICES_DIR . '/hotel/classes.php';
    require_once TLOGIC_SERVICES_DIR . '/ticket/classes.php';
	require_once TLOGIC_SERVICES_DIR . '/car/classes.php';
	require_once TLOGIC_SERVICES_DIR . '/transfer/classes.php';
}

/**
 * Load all service frontend code.
 */
function tlogic_load_service_frontends()
{
    // Hotel
	require_once TLOGIC_SERVICES_DIR . '/hotel/frontend.php';
	require_once TLOGIC_SERVICES_DIR . '/hotel/shortcodes.php';
	require_once TLOGIC_SERVICES_DIR . '/hotel/ttags.php';

    // Ticket
    require_once TLOGIC_SERVICES_DIR . '/ticket/frontend.php';
    require_once TLOGIC_SERVICES_DIR . '/ticket/shortcodes.php';
    require_once TLOGIC_SERVICES_DIR . '/ticket/ttags.php';

    // Rental Car
    require_once TLOGIC_SERVICES_DIR . '/car/frontend.php';
    require_once TLOGIC_SERVICES_DIR . '/car/shortcodes.php';
    require_once TLOGIC_SERVICES_DIR . '/car/ttags.php';
	
	// Transfer
	require_once TLOGIC_SERVICES_DIR . '/transfer/frontend.php';
    require_once TLOGIC_SERVICES_DIR . '/transfer/shortcodes.php';
    require_once TLOGIC_SERVICES_DIR . '/transfer/ttags.php';
}